spring:
  application:
    name: config-git
server:
  port: 13000

  #Spring Boot 1.5.X 以上默认开通了安全认证，所以要在配置文件 application.yml
  # 中添加此配置以将/actuator/refresh这个 Endpoint 暴露出来
management:
  endpoints:
    web:
      exposure:
        include: refresh