
spring:
  application:
    name: provider-user-feign    # 项目名称尽量用小写

eureka:
  client:
    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/,http://discovery:8762/eureka/   # 指定注册中心的地址 集群
      defaultZone: http://discovery:8761/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true
server:
  port: 1001
feign:
  hystrix:
    enabled: true
