server:
  port: 8760                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    # eureka.client.registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。
     # 单机时不开启 设为false
    registerWithEureka: false
    # eureka.client.fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，
    # 不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756

#     server.port：为了与后续要进行注册的服务区分，这里将服务注册中心的端口设置为 7000。
#     eureka.client.register-with-eureka：表示是否将自己注册到 Eureka Server，默认为 true。
#     eureka.client.fetch-registry：表示是否从 Eureka Server 获取注册信息，默认为 true。
#     eureka.client.service-url.defaultZone：设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址。默认是 http://localhost:8761/eureka ；多个地址可使用英文逗号（,）分隔。
